/* ============================================================
   THE TRADING DESK — ENCYCLOPEDIA DATA
   Add an entry: {t:title, cat:categoryKey, tag:'short label',
     def:'plain-language definition',
     why:'why a trader should care',
     watch:'the trap / nuance most people miss'}
   Categories are defined in TDESK.ENC_CATS below.
   ============================================================ */
window.TDESK = window.TDESK || {};

window.TDESK.ENC_CATS = [
  ['all','Everything'],
  ['structure','Market Structure'],
  ['options','Options'],
  ['futures','Futures'],
  ['greeks','The Greeks'],
  ['orders','Order Types'],
  ['risk','Risk & Money'],
  ['psych','Psychology'],
  ['modern','Today\u2019s Market']
];

window.TDESK.ENCYCLOPEDIA = [
/* ---------- MARKET STRUCTURE ---------- */
{t:'Bid / Ask / Spread',cat:'structure',tag:'the two-sided market',
 def:'The bid is the highest price a buyer will pay right now; the ask (offer) is the lowest a seller will take. The gap between them is the spread.',
 why:'You buy at the ask and sell at the bid, so the spread is a cost you pay on every round trip before the trade even moves. Tight spreads mean liquidity; wide spreads mean you\u2019re paying up to get filled.',
 watch:'Illiquid names and far-OTM options can show a spread wider than your entire edge. A "great fill" on a wide market is often just you crossing the spread and paying the house.'},
{t:'Liquidity',cat:'structure',tag:'can you get out?',
 def:'How easily an asset can be bought or sold without moving its price. Deep liquidity = large size trades with little slippage.',
 why:'Liquidity is the difference between an idea and a position you can actually exit. It decides your slippage, your spread cost, and whether your stop fills near where you set it.',
 watch:'Liquidity evaporates exactly when you need it most — into news, at the open, and during flushes. The size you can trade calmly at noon is not the size you can trade in a panic.'},
{t:'Volume',cat:'structure',tag:'the lie detector',
 def:'The number of shares or contracts traded over a period. It measures participation, not direction.',
 why:'Volume confirms conviction. A breakout on heavy volume has real hands behind it; the same move on thin volume is often a trap that reverses once the algos are done.',
 watch:'Volume is context, not a signal. High volume at a top is distribution; high volume at a bottom is capitulation — the same number means opposite things depending on location.'},
{t:'Support & Resistance',cat:'structure',tag:'the spine of everything',
 def:'Support is a price where buyers have repeatedly stepped in; resistance is where sellers have. They are zones of remembered supply and demand, not exact lines.',
 why:'They are the reference points a huge share of traders watch simultaneously, which is exactly why price reacts around them. Everything from stops to targets keys off these levels.',
 watch:'A level that breaks often flips role — old resistance becomes support and vice versa. And the more times a level is tested, the weaker it usually gets, not stronger.'},
{t:'Market vs. Limit',cat:'orders',tag:'speed vs. price',
 def:'A market order fills immediately at the best available price. A limit order fills only at your price or better — or not at all.',
 why:'Market orders guarantee execution, not price. Limit orders guarantee price, not execution. Choosing wrong is how you either chase fills or miss the trade entirely.',
 watch:'Market orders into thin or fast markets can fill far from the last print. In options especially, a market order is how you hand the market maker free money — use marketable limits instead.'},
{t:'Stop Order',cat:'orders',tag:'the exit that triggers',
 def:'An order that becomes active only when price hits your stop level. A stop-market then fills at whatever\u2019s available; a stop-limit only fills at your limit or better.',
 why:'It\u2019s your pre-decided line in the sand — the mechanical way to cap a loss before emotion takes the wheel.',
 watch:'Stops are visible to the market as liquidity. Clustering them at obvious round numbers or just past a level is how "stop hunts" happen. And a stop-limit can leave you holding a loser if price gaps straight through your limit.'},
{t:'Slippage',cat:'orders',tag:'the fill you didn\u2019t expect',
 def:'The difference between the price you expected and the price you actually got.',
 why:'Slippage is a real, recurring cost that backtests and mental math ignore. Over hundreds of trades it can quietly erase a positive expectancy.',
 watch:'It\u2019s worst exactly where you\u2019re most tempted — market orders, fast moves, wide spreads, and the open. Budget for it; don\u2019t assume perfect fills.'},
/* ---------- OPTIONS ---------- */
{t:'Call & Put',cat:'options',tag:'the two building blocks',
 def:'A call gives the right to buy the underlying at the strike; a put gives the right to sell it at the strike, before expiration. You pay a premium for that right.',
 why:'Every options strategy, no matter how complex, is built from these two pieces (bought or sold). Understanding them cold is the entire foundation.',
 watch:'Buying options means you can lose 100% of the premium and time is against you every day. Being right on direction but wrong on timing still loses.'},
{t:'Strike & Expiration',cat:'options',tag:'price and clock',
 def:'The strike is the price the contract lets you transact at. Expiration is the date the contract dies. Together they define the contract.',
 why:'Strike sets how much the move has to cover before you profit; expiration sets how much time you\u2019re buying. They drive premium, probability, and how fast decay hits.',
 watch:'Cheap far-OTM options are cheap for a reason — the market is telling you they probably expire worthless. "Lottery ticket" pricing is honest pricing.'},
{t:'Intrinsic & Extrinsic Value',cat:'options',tag:'what you\u2019re actually paying for',
 def:'Intrinsic value is how far in-the-money the option is right now. Extrinsic (time) value is everything else — the premium for time and volatility.',
 why:'It tells you what part of the price is real equity and what part is a melting ice cube. Extrinsic value is what theta eats and what implied volatility inflates.',
 watch:'When you buy an out-of-the-money option, you\u2019re paying 100% extrinsic value — pure time and vol. If the move doesn\u2019t come fast, that\u2019s the part that bleeds to zero.'},
{t:'Implied Volatility (IV)',cat:'options',tag:'the market\u2019s fear gauge',
 def:'The market\u2019s forecast of how much the underlying will move, backed out of option prices. Higher IV = more expensive options.',
 why:'IV is often more important than direction. You can buy a call, be right on the move, and still lose because IV collapsed. It sets the price of everything you trade.',
 watch:'IV rises into known events (earnings, Fed) and crushes right after — the "IV crush." Buying premium the day before earnings is one of the most common beginner traps.'},
{t:'IV Rank & IV Percentile',cat:'options',tag:'is vol cheap or rich?',
 def:'IV Rank places current implied volatility on a 0\u2013100 scale versus its own past year. IV Percentile is the share of days over the year that IV was lower than today.',
 why:'Raw IV is meaningless without context — 40% is cheap for one name and expensive for another. Rank/percentile tells you whether to be a net buyer or seller of premium.',
 watch:'High IV rank means options are expensive to buy but rich to sell — and it usually means real risk is priced in. Selling "rich" premium into an event can be selling insurance right before the fire.'},
{t:'Expected Move',cat:'options',tag:'the priced-in range',
 def:'The move the options market is pricing before an event or expiration, roughly spot \u00d7 IV \u00d7 \u221a(days/365). It\u2019s the one-standard-deviation range.',
 why:'It\u2019s the market\u2019s own estimate of the range — a sanity check on your target and your risk. If your profit target sits outside the expected move, you\u2019re betting on a tail.',
 watch:'The expected move is a one-standard-deviation band, so price lands outside it roughly a third of the time. It\u2019s a probability cone, not a fence.'},
{t:'Assignment & Exercise',cat:'options',tag:'when contracts become shares',
 def:'Exercise is acting on your right to buy/sell at the strike. Assignment is being on the other side — obligated to deliver because someone exercised the option you sold.',
 why:'If you sell options, assignment risk is real, especially near expiration and around dividends. It can turn a small options position into a large, capital-heavy stock position overnight.',
 watch:'In-the-money short options can be assigned early — you don\u2019t control when. Holding short ITM calls through an ex-dividend date is a classic way to get assigned unexpectedly.'},
{t:'0DTE Options',cat:'modern',tag:'zero days to expiry',
 def:'Options expiring the same day they\u2019re traded. On the S&P 500 they now make up over half of index option volume.',
 why:'They\u2019ve reshaped intraday markets — dealer hedging of same-day options creates real, mechanical support and resistance during the session that didn\u2019t exist a decade ago.',
 watch:'0DTE is almost pure gamma and theta with no time cushion. The leverage cuts both ways in minutes; most retail 0DTE volume is closer to a slot machine than a strategy.'},
/* ---------- THE GREEKS ---------- */
{t:'Delta',cat:'greeks',tag:'directional exposure',
 def:'How much an option\u2019s price moves per $1 move in the underlying. A 0.50 delta option gains about $0.50 for every $1 up in the stock; it also approximates the odds of finishing in-the-money.',
 why:'Delta is your directional exposure in a single number. It tells you how "stock-like" your position is and lets you compare positions across strikes on equal footing.',
 watch:'Delta isn\u2019t constant — it changes as price moves (that\u2019s gamma). A position that feels balanced can become dangerously directional after a fast move.'},
{t:'Gamma',cat:'greeks',tag:'the accelerator',
 def:'The rate of change of delta. High gamma means your directional exposure shifts quickly as the underlying moves.',
 why:'Gamma is why options accelerate. It\u2019s highest at-the-money and near expiration, which is exactly why short-dated ATM options feel explosive — small moves swing your P&L fast.',
 watch:'Gamma is a double-edged sword: it supercharges winners and detonates losers. Being short gamma (selling options) means the market can run you over faster than you can hedge.'},
{t:'Theta',cat:'greeks',tag:'the melting clock',
 def:'How much value an option loses per day from the passage of time alone, all else equal.',
 why:'Theta is the rent option buyers pay and option sellers collect. It explains why being right slowly still loses money when you\u2019re long premium.',
 watch:'Theta isn\u2019t linear — decay accelerates into the final weeks and days. The last week of an option\u2019s life is where time value evaporates fastest.'},
{t:'Vega',cat:'greeks',tag:'sensitivity to fear',
 def:'How much an option\u2019s price changes for a one-point move in implied volatility.',
 why:'Vega is why you can nail the direction and still lose. Long options are long vega (you want IV up); short options are short vega (you want IV down / crush).',
 watch:'Vega is largest in longer-dated, at-the-money options. Buying high-vega premium into an event and eating the post-event IV crush is a textbook way to lose on a correct call.'},
{t:'Vanna & Charm',cat:'greeks',tag:'the second-order forces',
 def:'Vanna is how delta shifts when volatility changes; charm is how delta shifts as time passes. Both describe how dealers must re-hedge without price even moving.',
 why:'These second-order Greeks drive real, mechanical flows — the "vanna rally" into a calm tape and the "charm" pin into Friday expiration are dealer hedging you can anticipate.',
 watch:'Vanna and charm walls sit at different strikes than gamma walls. Traders who only watch gamma miss where the market actually gets pulled as vol and time shift.'},
/* ---------- FUTURES ---------- */
{t:'Futures Contract',cat:'futures',tag:'leverage with a schedule',
 def:'A standardized agreement to buy or sell an asset at a set price on a future date. Index, energy, metal, and rate futures let you trade the whole market with one instrument.',
 why:'Futures offer deep liquidity, nearly 24-hour access, and defined contract specs. They\u2019re how professionals trade the index directly instead of through an ETF.',
 watch:'Built-in leverage means small moves are large dollars. One ES point is $50; the contract can move dozens of points in minutes. Futures reward respect for size and punish everything else.'},
{t:'Multiplier & Tick Value',cat:'futures',tag:'what a point is worth',
 def:'The multiplier converts a price move into dollars; the tick is the smallest price increment and its dollar value. ES: $50/point, 0.25 tick = $12.50.',
 why:'You cannot size a futures trade without this. Your stop distance in ticks times the tick value is your dollar risk — get it wrong and one "small" stop is a blown day.',
 watch:'Micro contracts (MES, MNQ, MCL) are 1/10 the size and exist precisely so you can learn without full-size risk. Starting on full-size ES is how new futures traders get carried out.'},
{t:'Contango & Backwardation',cat:'futures',tag:'the shape of the curve',
 def:'Contango is when further-dated futures cost more than near-dated (a normal, upward curve). Backwardation is the opposite — near-dated priced higher.',
 why:'The curve shape drives the hidden "roll cost" in futures and futures-based ETFs. Contango quietly bleeds long positions every roll; backwardation can pay you.',
 watch:'Volatility products (VIX futures ETFs) live in structural contango and decay relentlessly over time. "It always goes back up" is how people hold those to zero.'},
{t:'Rollover',cat:'futures',tag:'the contract expires — you don\u2019t',
 def:'Moving a position from an expiring contract month to the next active one before expiration or delivery.',
 why:'Futures contracts die on a schedule. If you trade them, you must roll or close before the front month expires — or risk delivery obligations.',
 watch:'Liquidity shifts to the new front month days before official expiration. Trading the old contract into its final days means trading a thinning, widening market.'},
/* ---------- RISK & MONEY ---------- */
{t:'Position Sizing',cat:'risk',tag:'80% of the game',
 def:'Deciding how much to trade so a single loss stays within a fixed, small percentage of your account — sizing from your stop distance, not your conviction.',
 why:'Sizing, not entries, is what keeps accounts alive. Risk 1% and you can be wrong ten times in a row and barely dent the account; risk 10% and a normal losing streak ends you.',
 watch:'Great traders survive losing streaks that would end everyone else — not because they\u2019re rarely wrong, but because being wrong costs them almost nothing. Size for the streak, not the trade.'},
{t:'Risk-to-Reward (R)',cat:'risk',tag:'the payoff ratio',
 def:'The ratio of what you risk to what you aim to make. Risking $1 to make $2 is a 2R trade. "R" becomes your unit of account.',
 why:'R lets you think in units instead of dollars and reveals whether a system even can work. Higher R means you can be right less than half the time and still print money.',
 watch:'A gorgeous 5R target you never reach is worse than a boring 1.5R you actually hit. Reward-to-risk only counts if the target is realistic within the expected move.'},
{t:'Expectancy',cat:'risk',tag:'the whole game in one number',
 def:'Your average profit or loss per trade over many trades: (win% \u00d7 avg win) \u2212 (loss% \u00d7 avg loss). Positive expectancy repeated with discipline is the entire edge.',
 why:'It collapses win rate, R, and consistency into one honest figure. A 40%-win system at 2.5R crushes a 70%-win system at 0.5R — expectancy is how you see that.',
 watch:'A positive expectancy still loses money if you can\u2019t survive the variance to realize it. Edge and survival are two different problems; you need both.'},
{t:'Drawdown',cat:'risk',tag:'the peak-to-trough pain',
 def:'The decline from an equity high to the subsequent low, usually in percent. It measures the worst stretch you\u2019d have had to sit through.',
 why:'Drawdown is what actually breaks traders — not the average, the worst run. A 50% drawdown needs a 100% gain just to recover, so avoiding deep holes matters more than chasing highs.',
 watch:'Backtests show you the drawdown; they don\u2019t make you feel it. The size that looks fine on a chart is often unbearable when it\u2019s your money in real time.'},
{t:'Correlation Risk',cat:'risk',tag:'one bet wearing five hats',
 def:'When positions that look separate actually move together — five tech longs are really one big bet on tech.',
 why:'Diversification only works if things are genuinely uncorrelated. Correlated positions stack risk silently, so a single sector move hits your whole book at once.',
 watch:'In a real panic, correlations converge toward one — everything falls together and the "hedges" fail exactly when you needed them. Stress-test what happens if it\u2019s all the same trade.'},
/* ---------- PSYCHOLOGY ---------- */
{t:'Revenge Trading',cat:'psych',tag:'the account killer',
 def:'Forcing a new trade to win back a loss — sizing up, abandoning rules, and chasing to make the pain stop.',
 why:'It\u2019s the single most destructive pattern in trading. The loss you\u2019re chasing is small; the tilt spiral that follows is what empties accounts.',
 watch:'The urge is strongest right after a loss, when judgment is worst. The fix is mechanical, not emotional: a hard rule that two losses in a row ends the session.'},
{t:'FOMO',cat:'psych',tag:'chasing green candles',
 def:'Fear of missing out — jumping into a move already underway because watching it run without you feels unbearable.',
 why:'FOMO entries come at the worst prices with no plan, no level, and no stop, right as the move is most extended. It\u2019s buying someone else\u2019s exit.',
 watch:'There is always another trade. The market prints thousands a year — missing one costs nothing; chasing one costs your stop and your discipline.'},
{t:'Discipline & The Plan',cat:'psych',tag:'rules over feelings',
 def:'Trading only setups that match a written plan, at pre-decided size, with pre-decided exits — regardless of how any single trade feels.',
 why:'Consistency comes from the plan, not from being smart in the moment. Written rules are how you outsource decisions to the calm version of yourself before money is on the line.',
 watch:'If it isn\u2019t written down, it doesn\u2019t exist — it\u2019s a suggestion your emotions will overrule. The plan only works if it\u2019s specific enough to be broken.'},
{t:'Loss Aversion',cat:'psych',tag:'why we hold losers',
 def:'The wiring that makes a loss hurt about twice as much as an equal gain feels good. It pushes traders to cut winners early and let losers run.',
 why:'It\u2019s the exact opposite of what works, and it\u2019s automatic. Naming it is how you catch yourself moving a stop "just this once" to avoid taking a small, correct loss.',
 watch:'"It\u2019s only a loss if I sell" is loss aversion talking. The market doesn\u2019t know or care about your entry price — a bad position is bad regardless of where you got in.'},
/* ---------- TODAY'S MARKET ---------- */
{t:'Gamma Exposure (GEX)',cat:'modern',tag:'dealer hedging as support/resistance',
 def:'A model of how much stock dealers must buy or sell to stay hedged as price moves, aggregated across all option strikes. Positive gamma dampens moves; negative gamma amplifies them.',
 why:'Dealer hedging is a real mechanical flow that pins price near big strikes (call/put walls) and can accelerate selloffs when gamma flips negative. It maps where the market gets sticky.',
 watch:'GEX is modeled, not observed — it assumes a dealer positioning convention and uses prior-day open interest, so it\u2019s a map of standing structure, not a live signal. Kairos is our tool for reading it.'},
{t:'Payment For Order Flow (PFOF)',cat:'modern',tag:'why your broker is "free"',
 def:'The practice where brokers route your orders to wholesale market makers, who pay the broker for that flow and fill your order internally.',
 why:'It\u2019s the business model behind commission-free trading. Understanding it explains who\u2019s on the other side of your "free" trade and why execution quality matters.',
 watch:'"Free" means you\u2019re the product being sold. It doesn\u2019t automatically mean bad fills, but it means your interests and your broker\u2019s revenue aren\u2019t perfectly aligned.'},
{t:'Dark Pools',cat:'modern',tag:'the trades you don\u2019t see live',
 def:'Private venues where large institutions trade big blocks away from the public order book to avoid moving the price against themselves.',
 why:'A large share of total volume trades off the lit exchanges. Prints that appear after the fact hint at where real size is being accumulated or distributed.',
 watch:'Dark-pool prints are delayed and don\u2019t reveal the aggressor side. Reading them as a real-time signal is mostly narrative — treat them as context, not a trigger.'},
{t:'Prediction Markets',cat:'modern',tag:'trading probability directly',
 def:'Markets where contracts pay out based on real-world outcomes (elections, econ data, events), pricing the crowd\u2019s live probability from 0 to 100%.',
 why:'They\u2019ve become a genuine asset class and a real-time gauge of event odds that often front-runs traditional headlines. Mispricings and thin books create tradeable edge.',
 watch:'Liquidity is uneven and resolution rules matter enormously — the edge is often in structure and mechanics, not the take. Delphi is our scanner for exactly this.'},
{t:'Prop Firms & Funded Accounts',cat:'modern',tag:'trading someone else\u2019s capital',
 def:'Firms that let you trade their capital after you pass an evaluation, splitting profits with you. The modern retail version runs on paid challenges with strict rules.',
 why:'They offer a path to size without risking your own savings — leverage on skill, not capital. For disciplined traders, the risk cap is a feature, not a bug.',
 watch:'The business model often profits from failed challenges, not trader payouts. Drawdown and consistency rules are strict by design; treat the fee as tuition you might not get back.'},
{t:'Algorithmic & HFT Flow',cat:'modern',tag:'who you\u2019re really trading against',
 def:'The bulk of modern volume is executed by algorithms — from slow institutional execution algos to high-frequency market makers operating in microseconds.',
 why:'It sets the texture of the tape: the fast wicks, the stop runs, the liquidity that vanishes and reappears. Knowing bots dominate the short-term print keeps you humble on timing.',
 watch:'You will not out-speed them, and the obvious level everyone sees is where they hunt liquidity. Your edge is patience and structure on higher timeframes, not reflexes on the 1-minute.'},
{t:'Circuit Breakers & Halts',cat:'structure',tag:'the market\u2019s emergency brakes',
 def:'Exchange rules that pause trading in a stock or the whole market after moves beyond set thresholds, to slow panic and let liquidity reset.',
 why:'Halts change the game mid-trade — you can be locked in a position you can\u2019t exit while news develops. Knowing they exist keeps position size honest around volatile names.',
 watch:'Reopens after a halt are often violent and gappy. Market orders sitting through a halt can fill far from where you expected when trading resumes.'}
];
