/* ============================================================
   THE TRADING DESK — ENCYCLOPEDIA DATA
   Add an entry: {t:title, cat:categoryKey, tag:'short label',
     def:'plain-language definition',
     why:'why a trader should care',
     watch:'the trap / nuance most people miss'}
   Categories are defined in TDESK.ENC_CATS below.
   ============================================================ */
window.TDESK = window.TDESK || {};

/* Tabs render in this order. The three PATH tabs come first because opening on
   79 unsorted cards is a wall, not a resource - a newcomer cannot tell which of
   them they are supposed to read first. Topic tabs follow for people who already
   know what they are looking for, and 'Everything' sits last as the escape
   hatch rather than the front door. */
window.TDESK.ENC_CATS = [
  ['lvl1','\u25cf Start here'],
  ['lvl2','\u25cf\u25cf Building'],
  ['lvl3','\u25cf\u25cf\u25cf Advanced'],
  ['structure','Market Structure'],
  ['options','Options'],
  ['futures','Futures'],
  ['greeks','The Greeks'],
  ['orders','Order Types'],
  ['risk','Risk & Money'],
  ['psych','Psychology'],
  ['modern','Today\u2019s Market'],
  ['all','Everything']
];

/* The reading path. Deliberately NOT every entry - a path that includes
   everything is just the index again. These are the terms that unlock the next
   ones; the rest are there when you go looking for them.
   Order inside each level is the order to read them in, not alphabetical. */
window.TDESK.ENC_PATH = {
  lvl1: [
    'Bid / Ask / Spread','Liquidity','Volume','Support & Resistance',
    'Market vs. Limit','Stop Order','Slippage',
    'Call & Put','Strike & Expiration',
    'Position Sizing','Risk-to-Reward (R)','Drawdown',
    'Discipline & The Plan','FOMO','Revenge Trading'
  ],
  lvl2: [
    'VWAP','Relative Volume (RVOL)','Average True Range (ATR)',
    'Opening Range & Initial Balance','Gaps & Gap Fill',
    'Bracket & OCO Orders','Trailing Stop','Time in Force',
    'Intrinsic & Extrinsic Value','Implied Volatility (IV)','Expected Move',
    'The Options Chain','Open Interest','Delta','Theta',
    'Futures Contract','Multiplier & Tick Value',
    'Expectancy','Margin & The Margin Call','Pattern Day Trader Rule',
    'Loss Aversion','Confirmation Bias'
  ],
  lvl3: [
    'Liquidity Sweep','Fair Value Gap (Imbalance)','Level 2 & Time and Sales',
    'Float & The Short Squeeze','IV Rank & IV Percentile',
    'Credit vs. Debit Spreads','Iron Condor','Volatility Skew',
    'Volatility Risk Premium','IV Crush','Pin Risk',
    'Gamma','Vega','Vanna & Charm',
    '0DTE Options','Gamma Exposure (GEX)','Zero-Gamma Flip',
    'Call Wall & Put Wall','OPEX & Triple Witching','Gamma Squeeze',
    'Contango & Backwardation','Correlation Risk','Risk of Ruin',
    'Volatility ETPs'
  ]
};

/* Shown above the grid on a path tab. One sentence on what this level is for
   and what you should be able to do by the end of it. */
window.TDESK.ENC_PATH_INTRO = {
  lvl1: ['Start here','The vocabulary you need before risking a dollar. What a price actually is, how an order behaves, what an option is, and the three risk ideas that decide whether you survive long enough to get good. Fifteen terms, in order.'],
  lvl2: ['Building','You can read a chart and place an order. Now: the tools that frame a session, the option mechanics that decide what you actually own, and the numbers that tell you whether your approach has an edge or a story.'],
  lvl3: ['Advanced','Where the modern market actually lives. Dealer positioning, volatility as a tradeable object, and the structural forces that move price when no news does. Read the first two levels before this one \u2014 it assumes them.']
};

window.TDESK.ENCYCLOPEDIA = [
/* ---------- MARKET STRUCTURE ---------- */
{t:'Bid / Ask / Spread',cat:'structure',tag:'the two-sided market',
 def:'The bid is the highest price a buyer will pay right now; the ask (offer) is the lowest a seller will take. The gap between them is the spread.',
 why:'You buy at the ask and sell at the bid, so the spread is a cost you pay on every round trip before the trade even moves. Tight spreads mean liquidity; wide spreads mean you\u2019re paying up to get filled.',
 watch:'Illiquid names and far-OTM options can show a spread wider than your entire edge. A "great fill" on a wide market is often just you crossing the spread and paying the house.'},
{t:'Liquidity',cat:'structure',tag:'can you get out?',
 def:'How easily an asset can be bought or sold without moving its price. Deep liquidity = large size trades with little slippage.',
 why:'Liquidity is the difference between an idea and a position you can actually exit. It decides your slippage, your spread cost, and whether your stop fills near where you set it.',
 watch:'Liquidity evaporates exactly when you need it most — into news, at the open, and during flushes. The size you can trade calmly at noon is not the size you can trade in a panic.'},
{t:'Volume',cat:'structure',tag:'the lie detector',
 def:'The number of shares or contracts traded over a period. It measures participation, not direction.',
 why:'Volume confirms conviction. A breakout on heavy volume has real hands behind it; the same move on thin volume is often a trap that reverses once the algos are done.',
 watch:'Volume is context, not a signal. High volume at a top is distribution; high volume at a bottom is capitulation — the same number means opposite things depending on location.'},
{t:'Support & Resistance',cat:'structure',tag:'the spine of everything',
 def:'Support is a price where buyers have repeatedly stepped in; resistance is where sellers have. They are zones of remembered supply and demand, not exact lines.',
 why:'They are the reference points a huge share of traders watch simultaneously, which is exactly why price reacts around them. Everything from stops to targets keys off these levels.',
 watch:'A level that breaks often flips role — old resistance becomes support and vice versa. And the more times a level is tested, the weaker it usually gets, not stronger.'},
{t:'VWAP',cat:'structure',tag:'the day\u2019s volume-weighted average price',
 def:'The average price of every share traded today, weighted by how much size traded there. It resets each session and is the reference price most institutional execution is measured against.',
 why:'Large orders are frequently benchmarked to VWAP, so it acts as a real gravitational level rather than a drawn one. Which side of it price holds tells you whether buyers or sellers have controlled the session so far.',
 watch:'VWAP is descriptive, not predictive. In a strong trend price can ride far above it for hours \u2014 \u201cit\u2019s extended from VWAP\u201d has funded a lot of bad short entries.'},
{t:'Relative Volume (RVOL)',cat:'structure',tag:'is this name actually in play?',
 def:'Today\u2019s volume compared with what this specific ticker normally trades at the same time of day. RVOL of 3 means three times its own typical pace.',
 why:'It is the single most useful screening filter in intraday trading. Published research on opening-range strategies found that restricting trades to abnormally high-volume names is what separates a profitable system from a mediocre one \u2014 the filter carries the edge.',
 watch:'High RVOL on a low-float name means violence, not opportunity. Volume tells you something is happening; it does not tell you the spread will let you out.'},
{t:'Average True Range (ATR)',cat:'structure',tag:'how far this thing normally moves',
 def:'The average size of a bar\u2019s full range over a lookback period, including any gap from the prior close. A volatility measure expressed in the instrument\u2019s own price units.',
 why:'It converts \u201chow much should I risk\u201d into an actual stop distance. Sizing by ATR lets a $400 stock and a $40 stock carry identical dollar risk, which is the only way to compare setups across a watchlist honestly.',
 watch:'ATR is backward-looking. It expands after volatility has already arrived, so an ATR stop set on a quiet week gets run instantly when the regime changes.'},
{t:'Opening Range & Initial Balance',cat:'structure',tag:'the session\u2019s first decision line',
 def:'The high and low of the first block of trading \u2014 commonly 15 or 30 minutes. The initial balance is the wider version: the full first hour, 9:30 to 10:30 ET.',
 why:'Overnight news, gaps and institutional repositioning all get priced in that window. The range it carves becomes the line the rest of the day negotiates around, and breaks of it are among the most-traded setups in the market.',
 watch:'On a rangebound morning the opening range gets broken in both directions before lunch. Without a volume or catalyst filter, trading every break is a fee-generating machine.'},
{t:'Liquidity Sweep',cat:'structure',tag:'the run above the obvious high',
 def:'A quick push through a level where stop orders visibly cluster \u2014 yesterday\u2019s high, the overnight low, a row of equal highs \u2014 followed by a sharp reversal back through it.',
 why:'Resting stops are the deepest pool of guaranteed liquidity on the chart. Large participants need that liquidity to fill size, so obvious levels get tested more often than a random level would.',
 watch:'A sweep is only identifiable after price comes back. Live, it is indistinguishable from a genuine breakout \u2014 which is exactly why it catches people on both sides.'},
{t:'Fair Value Gap (Imbalance)',cat:'structure',tag:'the space a fast move left behind',
 def:'A three-candle pattern where the move is violent enough that the first and third candles\u2019 wicks do not overlap, leaving a price band that traded with almost no two-sided activity.',
 why:'Gaps in participation often get revisited as price retraces to find the buyers or sellers who never got filled. It gives a mechanical, non-arbitrary place to look for an entry.',
 watch:'Drop to a low enough timeframe and there is an imbalance every few candles. When a concept can be found everywhere, it stops carrying information \u2014 and there is no peer-reviewed evidence that trading them has an edge.'},
{t:'Gaps & Gap Fill',cat:'structure',tag:'the space between yesterday and today',
 def:'A gap is when a session opens away from the prior close, leaving untraded price. A gap fill is price returning to that prior close.',
 why:'Gaps mark where information arrived while the market was shut, and the open is where the disagreement gets resolved. Whether a gap holds or fills within the first hour is one of the cleanest early reads on session strength.',
 watch:'\u201cGaps always fill\u201d is a myth carried by survivorship. Plenty never do, and the ones that never do are usually the ones with the strongest news behind them \u2014 exactly the wrong ones to fade.'},
{t:'Level 2 & Time and Sales',cat:'structure',tag:'the order book, and what actually printed',
 def:'Level 2 shows resting bids and offers stacked at each price. Time and sales \u2014 the tape \u2014 shows the trades that actually executed, at what price and size.',
 why:'The book shows intent; the tape shows commitment. Reading them together is how you tell a real absorption of supply from a wall of orders that vanishes the moment price arrives.',
 watch:'Displayed size can be pulled instantly, and a meaningful share of volume never appears in the lit book at all. Trading off Level 2 alone means trading off the part of the market most easily faked.'},
{t:'Float & The Short Squeeze',cat:'structure',tag:'why small share counts move violently',
 def:'Float is the number of shares actually available to trade, excluding insider and restricted holdings. A short squeeze is what happens when a heavily-shorted, low-float name rises and short sellers are forced to buy back into their own losses.',
 why:'Float explains why two companies with similar news move completely differently. A small float plus high short interest is the setup behind almost every parabolic single-name move you have watched happen.',
 watch:'Squeezes are the most seductive chart in the market and the fastest way to be liquidated. Borrow costs, halts and 40% reversals inside a minute make position sizing far more important than the thesis.'},
{t:'Market vs. Limit',cat:'orders',tag:'speed vs. price',
 def:'A market order fills immediately at the best available price. A limit order fills only at your price or better — or not at all.',
 why:'Market orders guarantee execution, not price. Limit orders guarantee price, not execution. Choosing wrong is how you either chase fills or miss the trade entirely.',
 watch:'Market orders into thin or fast markets can fill far from the last print. In options especially, a market order is how you hand the market maker free money — use marketable limits instead.'},
{t:'Stop Order',cat:'orders',tag:'the exit that triggers',
 def:'An order that becomes active only when price hits your stop level. A stop-market then fills at whatever\u2019s available; a stop-limit only fills at your limit or better.',
 why:'It\u2019s your pre-decided line in the sand — the mechanical way to cap a loss before emotion takes the wheel.',
 watch:'Stops are visible to the market as liquidity. Clustering them at obvious round numbers or just past a level is how "stop hunts" happen. And a stop-limit can leave you holding a loser if price gaps straight through your limit.'},
{t:'Slippage',cat:'orders',tag:'the fill you didn\u2019t expect',
 def:'The difference between the price you expected and the price you actually got.',
 why:'Slippage is a real, recurring cost that backtests and mental math ignore. Over hundreds of trades it can quietly erase a positive expectancy.',
 watch:'It\u2019s worst exactly where you\u2019re most tempted — market orders, fast moves, wide spreads, and the open. Budget for it; don\u2019t assume perfect fills.'},
/* ---------- OPTIONS ---------- */
{t:'Marketable Limit Order',cat:'orders',tag:'a fill now, with a ceiling',
 def:'A limit order priced at or through the current opposite side of the book \u2014 buying at the ask, selling at the bid \u2014 so it fills immediately like a market order but cannot fill worse than the price you set.',
 why:'It gives you the immediacy of a market order without handing the fill an open-ended price. In fast tape, wide spreads or thin options, this is the default professional entry.',
 watch:'\u201cImmediate\u201d is not \u201cguaranteed.\u201d If price runs past your limit before the order arrives, you simply do not get filled \u2014 and missing a fill on a stop-out is far worse than paying a penny.'},
{t:'Bracket & OCO Orders',cat:'orders',tag:'the exit decided before the entry',
 def:'A bracket attaches a profit target and a stop to a position at the moment it opens. OCO \u2014 one cancels other \u2014 links them, so filling either one cancels the other automatically.',
 why:'It removes the exit decision from the moment you are least capable of making it, which is while the position is moving against you. The plan gets encoded into the broker rather than your willpower.',
 watch:'A bracket is only as good as the levels in it. Placing a target and stop by round numbers instead of structure just automates a bad plan more efficiently.'},
{t:'Trailing Stop',cat:'orders',tag:'a stop that only moves one way',
 def:'A stop that follows price by a fixed distance or percentage as the trade works, and never moves backwards.',
 why:'It is the mechanical answer to cutting winners early. In strategies whose expectancy depends on a few large outliers \u2014 trend and momentum especially \u2014 letting the trail do the exiting is the whole edge.',
 watch:'A trail that is too tight converts every winner into a scratch, and volatility-blind trails get taken out by ordinary noise. Scale the distance to ATR, not to your comfort.'},
{t:'Time in Force',cat:'orders',tag:'how long the order stays alive',
 def:'The instruction that governs an order\u2019s lifespan. Day (or GFD) expires at the close. GTC persists across sessions. IOC fills what it can immediately and cancels the rest. FOK demands the entire size at once or nothing.',
 why:'It quietly determines whether you wake up in a position you forgot about. Day traders live on day orders precisely so nothing survives the bell without a decision.',
 watch:'GTC orders sitting far from price are a real hazard \u2014 an overnight gap or a news spike can fill an order you set weeks ago and no longer want.'},
{t:'Call & Put',cat:'options',tag:'the two building blocks',
 def:'A call gives the right to buy the underlying at the strike; a put gives the right to sell it at the strike, before expiration. You pay a premium for that right.',
 why:'Every options strategy, no matter how complex, is built from these two pieces (bought or sold). Understanding them cold is the entire foundation.',
 watch:'Buying options means you can lose 100% of the premium and time is against you every day. Being right on direction but wrong on timing still loses.'},
{t:'Strike & Expiration',cat:'options',tag:'price and clock',
 def:'The strike is the price the contract lets you transact at. Expiration is the date the contract dies. Together they define the contract.',
 why:'Strike sets how much the move has to cover before you profit; expiration sets how much time you\u2019re buying. They drive premium, probability, and how fast decay hits.',
 watch:'Cheap far-OTM options are cheap for a reason — the market is telling you they probably expire worthless. "Lottery ticket" pricing is honest pricing.'},
{t:'Intrinsic & Extrinsic Value',cat:'options',tag:'what you\u2019re actually paying for',
 def:'Intrinsic value is how far in-the-money the option is right now. Extrinsic (time) value is everything else — the premium for time and volatility.',
 why:'It tells you what part of the price is real equity and what part is a melting ice cube. Extrinsic value is what theta eats and what implied volatility inflates.',
 watch:'When you buy an out-of-the-money option, you\u2019re paying 100% extrinsic value — pure time and vol. If the move doesn\u2019t come fast, that\u2019s the part that bleeds to zero.'},
{t:'Implied Volatility (IV)',cat:'options',tag:'the market\u2019s fear gauge',
 def:'The market\u2019s forecast of how much the underlying will move, backed out of option prices. Higher IV = more expensive options.',
 why:'IV is often more important than direction. You can buy a call, be right on the move, and still lose because IV collapsed. It sets the price of everything you trade.',
 watch:'IV rises into known events (earnings, Fed) and crushes right after — the "IV crush." Buying premium the day before earnings is one of the most common beginner traps.'},
{t:'IV Rank & IV Percentile',cat:'options',tag:'is vol cheap or rich?',
 def:'IV Rank places current implied volatility on a 0\u2013100 scale versus its own past year. IV Percentile is the share of days over the year that IV was lower than today.',
 why:'Raw IV is meaningless without context — 40% is cheap for one name and expensive for another. Rank/percentile tells you whether to be a net buyer or seller of premium.',
 watch:'High IV rank means options are expensive to buy but rich to sell — and it usually means real risk is priced in. Selling "rich" premium into an event can be selling insurance right before the fire.'},
{t:'Expected Move',cat:'options',tag:'the priced-in range',
 def:'The move the options market is pricing before an event or expiration, roughly spot \u00d7 IV \u00d7 \u221a(days/365). It\u2019s the one-standard-deviation range.',
 why:'It\u2019s the market\u2019s own estimate of the range — a sanity check on your target and your risk. If your profit target sits outside the expected move, you\u2019re betting on a tail.',
 watch:'The expected move is a one-standard-deviation band, so price lands outside it roughly a third of the time. It\u2019s a probability cone, not a fence.'},
{t:'Assignment & Exercise',cat:'options',tag:'when contracts become shares',
 def:'Exercise is acting on your right to buy/sell at the strike. Assignment is being on the other side — obligated to deliver because someone exercised the option you sold.',
 why:'If you sell options, assignment risk is real, especially near expiration and around dividends. It can turn a small options position into a large, capital-heavy stock position overnight.',
 watch:'In-the-money short options can be assigned early — you don\u2019t control when. Holding short ITM calls through an ex-dividend date is a classic way to get assigned unexpectedly.'},
{t:'The Options Chain',cat:'options',tag:'every contract, laid out',
 def:'The full grid of available contracts for one underlying: calls and puts, every strike, every expiration, with bid, ask, volume, open interest and implied volatility.',
 why:'It is the raw material for everything else \u2014 expected move, skew, dealer positioning, liquidity. Learning to read a chain quickly is the difference between trading options and guessing at them.',
 watch:'Quoted mid prices on illiquid strikes are fiction. If the bid is 0.40 and the ask is 1.10, the \u201cprice\u201d is not 0.75 \u2014 it is whatever a market maker decides to give you.'},
{t:'Open Interest',cat:'options',tag:'contracts still outstanding',
 def:'The number of option contracts currently open at a strike \u2014 positions that have been entered and not yet closed or expired. Unlike volume, it does not reset daily.',
 why:'It measures where real positioning is parked, which is why every dealer-positioning model is built on it. Heavy open interest at a strike is where hedging pressure concentrates.',
 watch:'Open interest updates once overnight, so intraday it is always stale. It also cannot tell you who is long and who is short \u2014 every model that uses it has to assume that part.'},
{t:'Credit vs. Debit Spreads',cat:'options',tag:'getting paid vs. paying',
 def:'A vertical spread buys one option and sells another at a different strike in the same expiration. Take in money and it is a credit spread; pay money and it is a debit spread. Both cap the maximum loss.',
 why:'Spreads are how you express a view with defined risk. Credit spreads profit from time and stability; debit spreads profit from movement. The structure decides which force is working for you.',
 watch:'A high win rate on credit spreads hides the payoff. Collecting $1.00 against $9.00 of risk needs roughly nine wins per loss just to break even before costs \u2014 the losses are rare and enormous.'},
{t:'Iron Condor',cat:'options',tag:'selling both sides of the range',
 def:'A call credit spread above the market combined with a put credit spread below it. Maximum profit if price finishes between the short strikes at expiration.',
 why:'It is the standard defined-risk way to sell a range, and the most common structure used to harvest the tendency for implied volatility to exceed what actually gets delivered.',
 watch:'Two short strikes means two ways to be wrong. The position is short volatility and short gamma, so the day it breaks tends to break far \u2014 and adjusting a condor mid-move usually converts a manageable loss into a larger one.'},
{t:'Covered Call',cat:'options',tag:'renting out shares you own',
 def:'Owning 100 shares and selling a call against them. You keep the premium; if price closes above the strike, your shares are called away at that price.',
 why:'It generates income from a holding and lowers the effective cost basis, which is why it is the most common first options strategy at broker level 2.',
 watch:'You have sold your upside. In a strong run the stock leaves without you while you keep a small premium \u2014 and the downside remains fully yours the whole time.'},
{t:'Cash-Secured Put',cat:'options',tag:'getting paid to set a buy limit',
 def:'Selling a put while holding enough cash to buy the shares if assigned. Either the option expires worthless and you keep the premium, or you buy the stock at your chosen strike.',
 why:'It is a way to be paid for patience on a name you actually want to own. Combined with covered calls afterwards, it forms the strategy commonly called the wheel.',
 watch:'The risk profile is nearly identical to owning the stock outright. If it drops 40%, you are assigned at your strike and holding the loss \u2014 the premium covers a rounding error of it.'},
{t:'LEAPS',cat:'options',tag:'long-dated options as leveraged ownership',
 def:'Long-term equity anticipation securities \u2014 options expiring roughly a year or more out. High delta, low relative theta, used as a capital-efficient substitute for owning shares.',
 why:'A deep in-the-money LEAPS call behaves much like the stock at a fraction of the capital, which is why long-horizon investors use them to express multi-year conviction with leverage.',
 watch:'Leverage compresses the timeline your thesis is allowed to take. Being right eighteen months after expiration pays exactly nothing, and the spreads on long-dated contracts are wide.'},
{t:'Volatility Skew',cat:'options',tag:'why puts cost more than calls',
 def:'The pattern of implied volatility across strikes. In index options, downside puts almost always carry higher implied volatility than equidistant upside calls.',
 why:'Skew is the market pricing the fact that crashes happen faster than rallies, and that demand for protection is structural. It is where the market\u2019s fear is quoted directly.',
 watch:'Skew is not free money. Selling expensive puts collects the premium and inherits precisely the risk that made them expensive in the first place.'},
{t:'Volatility Risk Premium',cat:'options',tag:'implied usually exceeds realised',
 def:'The persistent tendency for implied volatility to price a larger move than the underlying actually delivers. It is the compensation option sellers earn for carrying event risk.',
 why:'This is the actual source of return behind every premium-selling strategy \u2014 condors, credit spreads, covered calls. Without it, those strategies would be coin flips minus commissions.',
 watch:'The premium is a payment for taking real risk, not a market inefficiency. It is collected in small regular amounts and paid back in rare enormous ones \u2014 survive those and you keep it, size wrong and you do not.'},
{t:'IV Crush',cat:'options',tag:'the earnings-day trap',
 def:'The sharp collapse in implied volatility immediately after a scheduled event resolves \u2014 most commonly the morning after earnings.',
 why:'It explains the most common beginner shock in options: the stock moved in your direction and the option still lost money. The uncertainty premium you paid for vanished the instant the news landed.',
 watch:'Being directionally right is not enough into a known event. If the move is smaller than what was priced, long premium loses regardless of direction.'},
{t:'Pin Risk',cat:'options',tag:'expiring right at the strike',
 def:'The uncertainty when the underlying settles at or extremely near a short strike at expiration, leaving you unsure whether you will be assigned.',
 why:'You can finish the day flat on paper and open Monday holding an unhedged 100-share position, which is a genuine account event rather than a rounding error.',
 watch:'Prices cluster at heavy strikes on expiration \u2014 this is documented in peer-reviewed research, not folklore. The cheapest fix is closing short options that finish near the money instead of letting them expire.'},
{t:'0DTE Options',cat:'modern',tag:'zero days to expiry',
 def:'Options expiring the same day they\u2019re traded. On the S&P 500 they now make up over half of index option volume.',
 why:'They\u2019ve reshaped intraday markets — dealer hedging of same-day options creates real, mechanical support and resistance during the session that didn\u2019t exist a decade ago.',
 watch:'0DTE is almost pure gamma and theta with no time cushion. The leverage cuts both ways in minutes; most retail 0DTE volume is closer to a slot machine than a strategy.'},
/* ---------- THE GREEKS ---------- */
{t:'Delta',cat:'greeks',tag:'directional exposure',
 def:'How much an option\u2019s price moves per $1 move in the underlying. A 0.50 delta option gains about $0.50 for every $1 up in the stock; it also approximates the odds of finishing in-the-money.',
 why:'Delta is your directional exposure in a single number. It tells you how "stock-like" your position is and lets you compare positions across strikes on equal footing.',
 watch:'Delta isn\u2019t constant — it changes as price moves (that\u2019s gamma). A position that feels balanced can become dangerously directional after a fast move.'},
{t:'Gamma',cat:'greeks',tag:'the accelerator',
 def:'The rate of change of delta. High gamma means your directional exposure shifts quickly as the underlying moves.',
 why:'Gamma is why options accelerate. It\u2019s highest at-the-money and near expiration, which is exactly why short-dated ATM options feel explosive — small moves swing your P&L fast.',
 watch:'Gamma is a double-edged sword: it supercharges winners and detonates losers. Being short gamma (selling options) means the market can run you over faster than you can hedge.'},
{t:'Theta',cat:'greeks',tag:'the melting clock',
 def:'How much value an option loses per day from the passage of time alone, all else equal.',
 why:'Theta is the rent option buyers pay and option sellers collect. It explains why being right slowly still loses money when you\u2019re long premium.',
 watch:'Theta isn\u2019t linear — decay accelerates into the final weeks and days. The last week of an option\u2019s life is where time value evaporates fastest.'},
{t:'Vega',cat:'greeks',tag:'sensitivity to fear',
 def:'How much an option\u2019s price changes for a one-point move in implied volatility.',
 why:'Vega is why you can nail the direction and still lose. Long options are long vega (you want IV up); short options are short vega (you want IV down / crush).',
 watch:'Vega is largest in longer-dated, at-the-money options. Buying high-vega premium into an event and eating the post-event IV crush is a textbook way to lose on a correct call.'},
{t:'Vanna & Charm',cat:'greeks',tag:'the second-order forces',
 def:'Vanna is how delta shifts when volatility changes; charm is how delta shifts as time passes. Both describe how dealers must re-hedge without price even moving.',
 why:'These second-order Greeks drive real, mechanical flows — the "vanna rally" into a calm tape and the "charm" pin into Friday expiration are dealer hedging you can anticipate.',
 watch:'Vanna and charm walls sit at different strikes than gamma walls. Traders who only watch gamma miss where the market actually gets pulled as vol and time shift.'},
/* ---------- FUTURES ---------- */
{t:'Rho',cat:'greeks',tag:'sensitivity to interest rates',
 def:'How much an option\u2019s price changes when risk-free interest rates move one percentage point. Positive for calls, negative for puts, and larger the further out the expiration.',
 why:'It is the forgotten greek that stopped being forgettable once rates moved off zero. On LEAPS and long-dated positions, the rate assumption is a real component of the price.',
 watch:'Rho is negligible on short-dated contracts \u2014 for a 0DTE trade it is noise. Its relevance scales with time to expiration, so judge it by horizon, not by habit.'},
{t:'Futures Contract',cat:'futures',tag:'leverage with a schedule',
 def:'A standardized agreement to buy or sell an asset at a set price on a future date. Index, energy, metal, and rate futures let you trade the whole market with one instrument.',
 why:'Futures offer deep liquidity, nearly 24-hour access, and defined contract specs. They\u2019re how professionals trade the index directly instead of through an ETF.',
 watch:'Built-in leverage means small moves are large dollars. One ES point is $50; the contract can move dozens of points in minutes. Futures reward respect for size and punish everything else.'},
{t:'Multiplier & Tick Value',cat:'futures',tag:'what a point is worth',
 def:'The multiplier converts a price move into dollars; the tick is the smallest price increment and its dollar value. ES: $50/point, 0.25 tick = $12.50.',
 why:'You cannot size a futures trade without this. Your stop distance in ticks times the tick value is your dollar risk — get it wrong and one "small" stop is a blown day.',
 watch:'Micro contracts (MES, MNQ, MCL) are 1/10 the size and exist precisely so you can learn without full-size risk. Starting on full-size ES is how new futures traders get carried out.'},
{t:'Contango & Backwardation',cat:'futures',tag:'the shape of the curve',
 def:'Contango is when further-dated futures cost more than near-dated (a normal, upward curve). Backwardation is the opposite — near-dated priced higher.',
 why:'The curve shape drives the hidden "roll cost" in futures and futures-based ETFs. Contango quietly bleeds long positions every roll; backwardation can pay you.',
 watch:'Volatility products (VIX futures ETFs) live in structural contango and decay relentlessly over time. "It always goes back up" is how people hold those to zero.'},
{t:'Rollover',cat:'futures',tag:'the contract expires — you don\u2019t',
 def:'Moving a position from an expiring contract month to the next active one before expiration or delivery.',
 why:'Futures contracts die on a schedule. If you trade them, you must roll or close before the front month expires — or risk delivery obligations.',
 watch:'Liquidity shifts to the new front month days before official expiration. Trading the old contract into its final days means trading a thinning, widening market.'},
/* ---------- RISK & MONEY ---------- */
{t:'Position Sizing',cat:'risk',tag:'80% of the game',
 def:'Deciding how much to trade so a single loss stays within a fixed, small percentage of your account — sizing from your stop distance, not your conviction.',
 why:'Sizing, not entries, is what keeps accounts alive. Risk 1% and you can be wrong ten times in a row and barely dent the account; risk 10% and a normal losing streak ends you.',
 watch:'Great traders survive losing streaks that would end everyone else — not because they\u2019re rarely wrong, but because being wrong costs them almost nothing. Size for the streak, not the trade.'},
{t:'Risk-to-Reward (R)',cat:'risk',tag:'the payoff ratio',
 def:'The ratio of what you risk to what you aim to make. Risking $1 to make $2 is a 2R trade. "R" becomes your unit of account.',
 why:'R lets you think in units instead of dollars and reveals whether a system even can work. Higher R means you can be right less than half the time and still print money.',
 watch:'A gorgeous 5R target you never reach is worse than a boring 1.5R you actually hit. Reward-to-risk only counts if the target is realistic within the expected move.'},
{t:'Expectancy',cat:'risk',tag:'the whole game in one number',
 def:'Your average profit or loss per trade over many trades: (win% \u00d7 avg win) \u2212 (loss% \u00d7 avg loss). Positive expectancy repeated with discipline is the entire edge.',
 why:'It collapses win rate, R, and consistency into one honest figure. A 40%-win system at 2.5R crushes a 70%-win system at 0.5R — expectancy is how you see that.',
 watch:'A positive expectancy still loses money if you can\u2019t survive the variance to realize it. Edge and survival are two different problems; you need both.'},
{t:'Drawdown',cat:'risk',tag:'the peak-to-trough pain',
 def:'The decline from an equity high to the subsequent low, usually in percent. It measures the worst stretch you\u2019d have had to sit through.',
 why:'Drawdown is what actually breaks traders — not the average, the worst run. A 50% drawdown needs a 100% gain just to recover, so avoiding deep holes matters more than chasing highs.',
 watch:'Backtests show you the drawdown; they don\u2019t make you feel it. The size that looks fine on a chart is often unbearable when it\u2019s your money in real time.'},
{t:'Correlation Risk',cat:'risk',tag:'one bet wearing five hats',
 def:'When positions that look separate actually move together — five tech longs are really one big bet on tech.',
 why:'Diversification only works if things are genuinely uncorrelated. Correlated positions stack risk silently, so a single sector move hits your whole book at once.',
 watch:'In a real panic, correlations converge toward one — everything falls together and the "hedges" fail exactly when you needed them. Stress-test what happens if it\u2019s all the same trade.'},
/* ---------- PSYCHOLOGY ---------- */
{t:'Risk of Ruin',cat:'risk',tag:'the odds the account never recovers',
 def:'The probability that a string of losses reduces capital below the point where the strategy can continue \u2014 driven by win rate, payoff ratio and, above all, how much is risked per trade.',
 why:'It reframes the real question. A strategy with a genuine edge still goes to zero if position size is large enough, because a losing streak long enough to break it is a statistical certainty given time.',
 watch:'Risking 10% per trade means a ten-trade losing streak is fatal, and ten losses in a row happen to good strategies routinely. Survival is a sizing decision, not a skill decision.'},
{t:'Sharpe Ratio',cat:'risk',tag:'return per unit of volatility',
 def:'Return above the risk-free rate, divided by the standard deviation of those returns. A standard way to compare strategies that produce different amounts of turbulence.',
 why:'It stops raw return from being the only scoreboard. A strategy earning 20% with mild swings is a different product from one earning 20% through repeated 50% drawdowns.',
 watch:'Sharpe treats upside and downside volatility identically and badly flatters strategies that sell options \u2014 steady small gains score well right up until the tail arrives. Always read it next to maximum drawdown.'},
{t:'Margin & The Margin Call',cat:'risk',tag:'trading with borrowed money',
 def:'Margin is buying power extended by a broker against your account value. A margin call is the demand to add funds or reduce positions when equity falls below the maintenance requirement.',
 why:'Leverage is the mechanism that turns a bad week into a closed account. It amplifies both directions, and the broker\u2019s risk desk is not obliged to wait for your thesis to work.',
 watch:'Brokers can liquidate positions without warning, and they typically do it at the worst possible moment \u2014 during the panic, not after it. Requirements can also be raised mid-crisis on the exact names you hold.'},
{t:'Pattern Day Trader Rule',cat:'risk',tag:'the US $25,000 threshold',
 def:'A FINRA rule: place four or more day trades within five business days in a margin account and you are flagged a pattern day trader, which requires maintaining at least $25,000 in equity.',
 why:'It is the practical constraint that shapes how most US retail traders start \u2014 driving people toward cash accounts, swing horizons, futures or offshore brokers before they have decided whether any of those actually suit them.',
 watch:'Getting flagged below the threshold restricts the account until it is resolved. Building a strategy that requires more day trades than your account structure permits is a planning failure, not a market one.'},
{t:'Revenge Trading',cat:'psych',tag:'the account killer',
 def:'Forcing a new trade to win back a loss — sizing up, abandoning rules, and chasing to make the pain stop.',
 why:'It\u2019s the single most destructive pattern in trading. The loss you\u2019re chasing is small; the tilt spiral that follows is what empties accounts.',
 watch:'The urge is strongest right after a loss, when judgment is worst. The fix is mechanical, not emotional: a hard rule that two losses in a row ends the session.'},
{t:'FOMO',cat:'psych',tag:'chasing green candles',
 def:'Fear of missing out — jumping into a move already underway because watching it run without you feels unbearable.',
 why:'FOMO entries come at the worst prices with no plan, no level, and no stop, right as the move is most extended. It\u2019s buying someone else\u2019s exit.',
 watch:'There is always another trade. The market prints thousands a year — missing one costs nothing; chasing one costs your stop and your discipline.'},
{t:'Discipline & The Plan',cat:'psych',tag:'rules over feelings',
 def:'Trading only setups that match a written plan, at pre-decided size, with pre-decided exits — regardless of how any single trade feels.',
 why:'Consistency comes from the plan, not from being smart in the moment. Written rules are how you outsource decisions to the calm version of yourself before money is on the line.',
 watch:'If it isn\u2019t written down, it doesn\u2019t exist — it\u2019s a suggestion your emotions will overrule. The plan only works if it\u2019s specific enough to be broken.'},
{t:'Loss Aversion',cat:'psych',tag:'why we hold losers',
 def:'The wiring that makes a loss hurt about twice as much as an equal gain feels good. It pushes traders to cut winners early and let losers run.',
 why:'It\u2019s the exact opposite of what works, and it\u2019s automatic. Naming it is how you catch yourself moving a stop "just this once" to avoid taking a small, correct loss.',
 watch:'"It\u2019s only a loss if I sell" is loss aversion talking. The market doesn\u2019t know or care about your entry price — a bad position is bad regardless of where you got in.'},
/* ---------- TODAY'S MARKET ---------- */
{t:'Confirmation Bias',cat:'psych',tag:'shopping for agreement',
 def:'The tendency to seek out and weight information that supports a position you already hold, while discounting anything that contradicts it.',
 why:'It is why traders scroll for bullish takes after buying. Once capital is committed, the mind quietly switches from evaluating the trade to defending it \u2014 and the research you do after entry is rarely research.',
 watch:'The cure is procedural, not emotional: write down what would prove you wrong before entering, and check for that specifically rather than for reassurance.'},
{t:'Recency Bias',cat:'psych',tag:'over-weighting what just happened',
 def:'Treating the most recent outcomes as more representative than they are \u2014 assuming the current regime, streak or volatility level is the permanent state of the market.',
 why:'It drives the classic cycle: size up after three wins, abandon a strategy after three losses, and buy volatility protection only once it has already become expensive.',
 watch:'It attacks strategy evaluation hardest. Judging a system on ten trades tells you almost nothing, but ten trades is exactly the sample size at which people quit or double down.'},
{t:'Survivorship Bias',cat:'psych',tag:'the accounts that blew up don\u2019t post',
 def:'Drawing conclusions from the visible winners of a process while the failures are invisible \u2014 because they stopped participating, deleted the posts, or never appeared at all.',
 why:'It is the single largest distortion in retail trading education. Every strategy on social media looks profitable because the traders it destroyed are not there to say otherwise, and the screenshots are self-selected by definition.',
 watch:'This applies to backtests too. A study run only on today\u2019s index members has quietly excluded every company that went to zero \u2014 which is precisely the outcome you needed to measure.'},
{t:'Gamma Exposure (GEX)',cat:'modern',tag:'dealer hedging as support/resistance',
 def:'A model of how much stock dealers must buy or sell to stay hedged as price moves, aggregated across all option strikes. Positive gamma dampens moves; negative gamma amplifies them.',
 why:'Dealer hedging is a real mechanical flow that pins price near big strikes (call/put walls) and can accelerate selloffs when gamma flips negative. It maps where the market gets sticky.',
 watch:'GEX is modeled, not observed — it assumes a dealer positioning convention and uses prior-day open interest, so it\u2019s a map of standing structure, not a live signal. Kairos is our tool for reading it.'},
{t:'Payment For Order Flow (PFOF)',cat:'modern',tag:'why your broker is "free"',
 def:'The practice where brokers route your orders to wholesale market makers, who pay the broker for that flow and fill your order internally.',
 why:'It\u2019s the business model behind commission-free trading. Understanding it explains who\u2019s on the other side of your "free" trade and why execution quality matters.',
 watch:'"Free" means you\u2019re the product being sold. It doesn\u2019t automatically mean bad fills, but it means your interests and your broker\u2019s revenue aren\u2019t perfectly aligned.'},
{t:'Dark Pools',cat:'modern',tag:'the trades you don\u2019t see live',
 def:'Private venues where large institutions trade big blocks away from the public order book to avoid moving the price against themselves.',
 why:'A large share of total volume trades off the lit exchanges. Prints that appear after the fact hint at where real size is being accumulated or distributed.',
 watch:'Dark-pool prints are delayed and don\u2019t reveal the aggressor side. Reading them as a real-time signal is mostly narrative — treat them as context, not a trigger.'},
{t:'Prediction Markets',cat:'modern',tag:'trading probability directly',
 def:'Markets where contracts pay out based on real-world outcomes (elections, econ data, events), pricing the crowd\u2019s live probability from 0 to 100%.',
 why:'They\u2019ve become a genuine asset class and a real-time gauge of event odds that often front-runs traditional headlines. Mispricings and thin books create tradeable edge.',
 watch:'Liquidity is uneven and resolution rules matter enormously — the edge is often in structure and mechanics, not the take. Delphi is our scanner for exactly this.'},
{t:'Prop Firms & Funded Accounts',cat:'modern',tag:'trading someone else\u2019s capital',
 def:'Firms that let you trade their capital after you pass an evaluation, splitting profits with you. The modern retail version runs on paid challenges with strict rules.',
 why:'They offer a path to size without risking your own savings — leverage on skill, not capital. For disciplined traders, the risk cap is a feature, not a bug.',
 watch:'The business model often profits from failed challenges, not trader payouts. Drawdown and consistency rules are strict by design; treat the fee as tuition you might not get back.'},
{t:'Algorithmic & HFT Flow',cat:'modern',tag:'who you\u2019re really trading against',
 def:'The bulk of modern volume is executed by algorithms — from slow institutional execution algos to high-frequency market makers operating in microseconds.',
 why:'It sets the texture of the tape: the fast wicks, the stop runs, the liquidity that vanishes and reappears. Knowing bots dominate the short-term print keeps you humble on timing.',
 watch:'You will not out-speed them, and the obvious level everyone sees is where they hunt liquidity. Your edge is patience and structure on higher timeframes, not reflexes on the 1-minute.'},
{t:'Zero-Gamma Flip',cat:'modern',tag:'the line between two market regimes',
 def:'The modelled spot price at which aggregate dealer gamma crosses zero. Above it dealers are generally long gamma and hedging damps moves; below it they are short gamma and hedging amplifies them.',
 why:'It is a regime switch rather than a signal. Which side of it price sits on decides whether fades or breakouts are the right trade today \u2014 and getting that backwards is the most expensive dealer-flow mistake there is.',
 watch:'Every published flip level is a model output built on an assumed dealer convention and stale open interest. Two vendors will print two different levels for the same session, so trade the sign of the regime, not the decimals.'},
{t:'Call Wall & Put Wall',cat:'modern',tag:'where gamma stacks up',
 def:'The strikes above and below spot carrying the heaviest gamma concentration. They are commonly read as the practical ceiling and floor of a range while positive gamma dominates.',
 why:'Gamma does not spread evenly across strikes \u2014 it clusters. Those clusters are where hedging pressure concentrates, which makes them support and resistance with an actual mechanical cause rather than a drawn line.',
 watch:'Walls decay as their expiration approaches and rebuild afterwards. Marking ten of them guarantees price is always near one, which guarantees you always have an excuse to trade.'},
{t:'OPEX & Triple Witching',cat:'modern',tag:'when the map gets rebuilt',
 def:'Monthly options expiration, usually the third Friday. Four times a year it coincides with index futures and index option expiries \u2014 the quarterly event still called triple witching.',
 why:'Enormous open interest rolls off at once, so dealer positioning and every gamma level derived from it are reset overnight. Volume spikes and the structure that governed the last few weeks simply stops applying.',
 watch:'Pinning research is strongest for monthly expirations \u2014 follow-up work found weekly expiries pin considerably less. Borrowing monthly-OPEX confidence for an ordinary Tuesday is a standard error.'},
{t:'Gamma Squeeze',cat:'modern',tag:'hedging that feeds itself',
 def:'A feedback loop where heavy call buying forces dealers to buy the underlying to stay hedged, which lifts price, which increases their delta again, which forces more buying.',
 why:'It explains single-name moves that look impossible on fundamentals. The buying is mechanical and price-insensitive \u2014 the hedger is not expressing a view, only managing risk.',
 watch:'It unwinds as fast as it builds. When the calls expire or the flow stops, the same hedging runs in reverse with nothing underneath it \u2014 and it is nearly impossible to identify the top in real time.'},
{t:'Leveraged & Inverse ETFs',cat:'modern',tag:'daily objectives, not long-term ones',
 def:'Funds engineered to deliver a multiple \u2014 2x, 3x, or inverse \u2014 of an index\u2019s return for a single day. They rebalance their exposure daily to maintain that ratio.',
 why:'That daily rebalancing is real market flow. Academic work links the mechanical rebalancing of leveraged funds, alongside option hedging, to the intraday momentum observed into the closing bell.',
 watch:'The daily reset causes decay in choppy markets: an index can finish flat over a month while a 3x fund on it is meaningfully down. These are trading instruments and the prospectus says so plainly.'},
{t:'Volatility ETPs',cat:'modern',tag:'VIX exposure, with a cost attached',
 def:'Exchange-traded products such as VIXY and UVXY that hold VIX futures rather than the index itself, giving indirect and imperfect exposure to expected volatility.',
 why:'They are the most accessible way to trade or hedge volatility without an options account, which makes them a common proxy on dashboards \u2014 including this one.',
 watch:'VIX futures usually sit in contango, so these products bleed value continuously just from rolling. Long-dated holding is structurally a losing position, and the inverse versions have blown up before.'},
{t:'Overnight & 24-Hour Trading',cat:'modern',tag:'the session that never fully closes',
 def:'Extended sessions that now allow US equities and ETFs to trade nearly around the clock through alternative venues, well beyond the traditional pre-market and after-hours windows.',
 why:'Price discovery no longer waits for the opening bell, so overnight moves are increasingly where gaps get formed rather than simply revealed at 9:30.',
 watch:'Liquidity is a fraction of regular hours, spreads are far wider, and a single order can move price meaningfully. Stops placed for regular hours can execute at prices that would never have printed at midday.'},
{t:'Circuit Breakers & Halts',cat:'structure',tag:'the market\u2019s emergency brakes',
 def:'Exchange rules that pause trading in a stock or the whole market after moves beyond set thresholds, to slow panic and let liquidity reset.',
 why:'Halts change the game mid-trade — you can be locked in a position you can\u2019t exit while news develops. Knowing they exist keeps position size honest around volatile names.',
 watch:'Reopens after a halt are often violent and gappy. Market orders sitting through a halt can fill far from where you expected when trading resumes.'}
];
