/* ============================================================
   THE TRADING DESK — PATTERN LIBRARY DATA
   Edit here to add/change candlestick & chart patterns.
   candle format: [open, close, high, low]  (higher number = higher price)
   chart format:  pts:[[x,y]...] 0-100 space, optional lines/arr
   ============================================================ */
window.TDESK = window.TDESK || {};
window.TDESK.PATTERNS = [
/* ---- singles ---- */
{n:'Doji',cat:'single',side:'neut',c:[[50,50,68,32]],
 read:'Open and close land in the same spot — a dead heat between buyers and sellers.',
 ctx:'Matters most after an extended trend or at a key level, where indecision can precede a turn.',
 trap:'Mid-range dojis mean nothing. Indecision in the middle of nowhere is just noise.'},
{n:'Dragonfly Doji',cat:'single',side:'bull',c:[[58,58,61,22]],
 read:'Sellers drove price down hard; buyers shoved every bit of it back by the close.',
 ctx:'Strongest at support after a decline — the long lower tail is rejection of lower prices.',
 trap:'Without a level under it, it\u2019s one candle of noise. Wait for the next candle to confirm.'},
{n:'Gravestone Doji',cat:'single',side:'bear',c:[[42,42,78,39]],
 read:'Buyers pushed to the highs and got fully rejected — close back at the open.',
 ctx:'Watch for it at resistance after a run-up; the failed push exposes exhausted buyers.',
 trap:'In a strong uptrend a single rejection often just pauses the move. Confirmation first.'},
{n:'Hammer',cat:'single',side:'bull',c:[[48,57,60,18]],
 read:'A long lower wick with a small body up top — lows were bought aggressively.',
 ctx:'After a downtrend into support. The deeper the wick relative to body, the louder the message.',
 trap:'A hammer mid-fall is just a pause. Location makes the pattern, not the shape.'},
{n:'Inverted Hammer',cat:'single',side:'bull',c:[[44,52,84,42]],
 read:'An upper-wick probe after a decline — buyers tested higher and held the close.',
 ctx:'At the bottom of a downtrend; needs a bullish candle after it to mean anything.',
 trap:'Identical shape at a top is a shooting star — the bearish twin. Context decides which.'},
{n:'Hanging Man',cat:'single',side:'bear',c:[[57,48,60,18]],
 read:'Hammer shape, wrong neighborhood — a deep sell-off intraday after a rally.',
 ctx:'At the top of an uptrend it warns that sellers showed real size for the first time.',
 trap:'Often needs a red confirmation candle. Alone it\u2019s a warning light, not a turn.'},
{n:'Shooting Star',cat:'single',side:'bear',c:[[52,44,84,42]],
 read:'Buyers spiked it high and sellers slammed it back — the rally attempt failed.',
 ctx:'At resistance after an advance. The long upper wick is the trap closing on late buyers.',
 trap:'In strong momentum, one rejected push often just resets before continuation.'},
{n:'Bullish Spinning Top',cat:'single',side:'bull',c:[[45,55,72,28]],
 read:'Small green body, wicks both ways — a fight that buyers barely edged.',
 ctx:'In a downtrend it hints that selling pressure is losing its grip.',
 trap:'Spinning tops are pause candles. They suggest a turn — they never confirm one.'},
{n:'Bearish Spinning Top',cat:'single',side:'bear',c:[[55,45,72,28]],
 read:'Small red body with long wicks — sellers won the round, barely.',
 ctx:'In an uptrend it signals momentum cooling before a possible roll-over.',
 trap:'Same as its twin: a hint, not a signal. The next candle does the talking.'},
{n:'Bullish Marubozu',cat:'single',side:'bull',c:[[22,80,80,22]],
 read:'Open at the low, close at the high, no wicks — buyers in total control start to finish.',
 ctx:'Breaking out of a range or level, it shows conviction; institutions don\u2019t hide in these.',
 trap:'Chasing a giant marubozu means buying someone else\u2019s entire move. Late is late.'},
{n:'Bearish Marubozu',cat:'single',side:'bear',c:[[80,22,80,22]],
 read:'Open at the high, close at the low — sellers never let go of the wheel.',
 ctx:'Through support it signals genuine distribution, not a dip.',
 trap:'After an extended fall, the biggest red candle is often near the flush — not the start.'},
/* ---- doubles ---- */
{n:'Bullish Engulfing',cat:'double',side:'bull',c:[[56,42,59,39],[36,68,71,33]],
 read:'A green body swallows the prior red one whole — buyers seized full control.',
 ctx:'Highest quality at major support after a downtrend, ideally with rising volume.',
 trap:'Engulfing mid-range is common and meaningless. The level does the heavy lifting.'},
{n:'Bearish Engulfing',cat:'double',side:'bear',c:[[44,58,61,41],[64,32,67,29]],
 read:'A red body swallows the prior green one — sellers took the handoff hard.',
 ctx:'At resistance after a rally, it marks the spot late buyers got trapped.',
 trap:'In a roaring uptrend single engulfings get steamrolled. Trend strength matters.'},
{n:'Bullish Kicker',cat:'double',side:'bull',c:[[48,30,50,27],[58,82,85,56]],
 read:'A gap up that never looks back — sentiment flipped overnight, violently.',
 ctx:'Usually news-driven. One of the most forceful two-candle reversals there is.',
 trap:'Gaps invite chasing. The disciplined entry is the retest, not the open.'},
{n:'Bearish Kicker',cat:'double',side:'bear',c:[[52,70,73,50],[42,18,44,15]],
 read:'A gap down with zero recovery — holders woke up trapped.',
 ctx:'Often earnings or headline driven; respect it, gaps like this rarely fill fast.',
 trap:'Shorting the panic candle is chasing too. Let the first bounce show its hand.'},
{n:'Piercing Line',cat:'double',side:'bull',c:[[62,38,65,34],[30,52,56,27]],
 read:'Opens below the prior low, then closes above the midpoint of the red candle.',
 ctx:'A downtrend reversal cue at support — buyers reclaimed more than half the loss.',
 trap:'Closing below the midpoint makes it just a bounce. The 50% line is the bar.'},
{n:'Dark Cloud Cover',cat:'double',side:'bear',c:[[38,62,66,35],[70,48,73,44]],
 read:'Gaps above the prior high, then closes below the green candle\u2019s midpoint.',
 ctx:'At resistance it shows breakout buyers getting absorbed and reversed.',
 trap:'Same midpoint rule in reverse — a shallow push-back into the body proves little.'},
{n:'Tweezer Bottom',cat:'double',side:'bull',c:[[58,36,60,22],[36,54,57,22]],
 read:'Two candles reject the exact same low — a price the market refuses to sell below.',
 ctx:'The matched lows often mark a defended level; stronger with the second candle green.',
 trap:'Tweezers define a level, not a rocket. Trade the level\u2019s hold, not the pattern.'},
{n:'Tweezer Top',cat:'double',side:'bear',c:[[42,64,78,40],[64,46,78,43]],
 read:'Two candles rejected at the identical high — supply sitting at one price.',
 ctx:'Marks where sellers are stacked; a clean short reference if the level keeps holding.',
 trap:'Three touches of a high can also precede a breakout. Watch how price leaves.'},
{n:'Bullish Harami',cat:'double',side:'bull',c:[[68,32,71,29],[40,54,57,37]],
 read:'A small green candle inside the prior big red body — the selling stalled.',
 ctx:'After a steep decline it\u2019s the first sign sellers are exhausted, pending confirmation.',
 trap:'"Inside" means undecided. Without the follow-through candle it\u2019s just rest.'},
{n:'Bearish Harami',cat:'double',side:'bear',c:[[32,68,71,29],[60,46,63,43]],
 read:'A small red candle inside the prior big green body — the buying stalled.',
 ctx:'After a vertical run it hints at distribution beginning under the surface.',
 trap:'Strong trends print haramis constantly and keep going. Demand confirmation.'},
{n:'Rising Window',cat:'double',side:'bull',c:[[28,46,49,25],[56,74,77,53]],
 read:'A gap up between two candles — demand outran supply overnight.',
 ctx:'The gap zone itself becomes support; old resistance below it often flips.',
 trap:'Exhaustion gaps late in a trend look identical to breakaway gaps early in one.'},
{n:'Falling Window',cat:'double',side:'bear',c:[[72,54,75,51],[44,26,47,23]],
 read:'A gap down between two candles — supply overwhelmed every resting bid.',
 ctx:'The gap acts as resistance overhead; rallies into it tend to struggle.',
 trap:'"Gaps always fill" is a slogan, not a rule. Some fill in hours, some in years.'},
/* ---- multi (3+) ---- */
{n:'Morning Star',cat:'multi',side:'bull',c:[[70,44,73,41],[36,32,39,27],[40,66,70,37]],
 read:'Big red, tiny pause, big green — panic, indecision, then reversal in three acts.',
 ctx:'One of the more reliable bottoming structures at real support after a downtrend.',
 trap:'The third candle must close deep into the first red body. A weak third act voids it.'},
{n:'Evening Star',cat:'multi',side:'bear',c:[[30,56,59,27],[64,68,73,61],[60,34,63,30]],
 read:'Big green, stall at the highs, big red — euphoria rolling over in sequence.',
 ctx:'At resistance after an advance, it maps the exact handoff from buyers to sellers.',
 trap:'Same rule mirrored: the red candle must cut deep into the first green body.'},
{n:'Bullish Abandoned Baby',cat:'multi',side:'bull',c:[[70,46,72,42],[30,28,34,24],[42,68,71,39]],
 read:'A doji gapped away below everything, then a gap back up — the bottom got orphaned.',
 ctx:'Rare and forceful: the isolated doji shows capitulation no one wanted to own.',
 trap:'Both gaps must be real. Without true separation it\u2019s just a morning star.'},
{n:'Bearish Abandoned Baby',cat:'multi',side:'bear',c:[[30,54,58,27],[70,72,76,66],[58,32,61,29]],
 read:'A doji gapped above everything, then a gap back down — the top got orphaned.',
 ctx:'The stranded doji is peak euphoria; the gap down strands everyone who bought it.',
 trap:'Equally rare. If you\u2019re seeing them weekly, you\u2019re forcing the read.'},
{n:'Three White Soldiers',cat:'multi',side:'bull',c:[[24,44,46,21],[40,60,62,37],[56,78,81,53]],
 read:'Three strong green candles, each opening inside the last and closing higher.',
 ctx:'Out of a base or downtrend it signals steady, committed accumulation.',
 trap:'Three giant candles can also mean short-term exhaustion — late entries pay for it.'},
{n:'Three Black Crows',cat:'multi',side:'bear',c:[[76,56,79,53],[60,40,63,37],[44,22,47,19]],
 read:'Three heavy red candles stepping down in sequence — methodical distribution.',
 ctx:'Off a top it shows sellers pressing with patience, not panic. Trend change energy.',
 trap:'After the third crow the move is well known. Plan the pullback, not the chase.'},
{n:'Three Line Strike',cat:'multi',side:'bull',c:[[70,58,72,55],[60,47,62,44],[49,35,51,32],[31,76,79,28]],
 read:'Three red candles erased by one green bar that engulfs the entire sequence.',
 ctx:'A violent reset: everyone who shorted the three-candle slide is now trapped.',
 trap:'Statistically it\u2019s a continuation pattern more than a bottom call. Don\u2019t over-read it.'},
{n:'Three Inside Up',cat:'multi',side:'bull',c:[[70,38,72,35],[44,58,61,41],[55,76,79,52]],
 read:'A harami plus a confirmation close above the first candle\u2019s high.',
 ctx:'It\u2019s the harami done right — the third candle supplies the proof the pattern needs.',
 trap:'Entering on candle two is trading the hope, not the pattern. Wait for three.'},
{n:'Three Inside Down',cat:'multi',side:'bear',c:[[30,62,65,27],[56,42,59,39],[45,24,48,21]],
 read:'A bearish harami confirmed by a close below the first candle\u2019s low.',
 ctx:'The structured version of "the rally stalled" — stall, then proof.',
 trap:'Same discipline mirrored: the third candle is the pattern. Two is a guess.'},
{n:'Three Outside Up',cat:'multi',side:'bull',c:[[56,44,58,41],[40,62,65,37],[58,78,81,55]],
 read:'A bullish engulfing plus a third candle closing higher still.',
 ctx:'Engulfing with receipts — the follow-through removes the biggest failure mode.',
 trap:'By candle three the move is visible to everyone. Size for a pullback entry.'},
{n:'Three Outside Down',cat:'multi',side:'bear',c:[[44,56,59,41],[60,38,63,35],[42,22,45,19]],
 read:'A bearish engulfing confirmed by another lower close.',
 ctx:'Distribution confirmed; old support levels below become the working map.',
 trap:'Late shorts into confirmed weakness still need a stop above the structure.'},
/* ---- chart structures ---- */
{n:'Double Top',cat:'chart',side:'bear',pts:[[2,22],[22,72],[38,46],[58,72],[74,40],[98,12]],lines:[[20,46,84,46]],arr:'dn',
 read:'Two failed pushes at the same high with a valley between — the "M" shape.',
 ctx:'Triggers on the break of the valley low (the neckline), not at the second peak.',
 trap:'Until the neckline breaks it\u2019s just a range. Most "double tops" resolve upward.'},
{n:'Double Bottom',cat:'chart',side:'bull',pts:[[2,78],[22,28],[38,54],[58,28],[74,60],[98,88]],lines:[[20,54,84,54]],arr:'up',
 read:'Two defended lows with a bounce between — the "W" that ends downtrends.',
 ctx:'Confirmation is the close above the middle peak; the second low often undercuts slightly.',
 trap:'Buying the second low before confirmation is catching a knife with a story.'},
{n:'Triple Top',cat:'chart',side:'bear',pts:[[2,28],[16,70],[28,46],[42,72],[56,46],[70,70],[82,40],[98,12]],lines:[[14,46,86,46]],arr:'dn',
 read:'Three rejections at one price — supply parked there isn\u2019t leaving.',
 ctx:'Break of the twin valleys confirms; the more touches, the more obvious to everyone.',
 trap:'Levels tested repeatedly also break upward often. The third touch isn\u2019t destiny.'},
{n:'Triple Bottom',cat:'chart',side:'bull',pts:[[2,72],[16,30],[28,54],[42,28],[56,54],[70,30],[82,60],[98,88]],lines:[[14,54,86,54]],arr:'up',
 read:'Three holds of the same low — a level someone with size keeps defending.',
 ctx:'Confirmed by the break above the interior peaks, ideally on expanding volume.',
 trap:'Each retest weakens stops below it. The break that does come can be violent — either way.'},
{n:'Head & Shoulders',cat:'chart',side:'bear',pts:[[2,30],[14,58],[24,42],[40,82],[56,42],[68,58],[80,42],[98,10]],lines:[[20,42,84,42]],arr:'dn',
 read:'A higher high (the head) flanked by two lower peaks — the uptrend\u2019s last gasp.',
 ctx:'The neckline break is the pattern; the measured move targets roughly the head\u2019s height.',
 trap:'People see H&S in everything. No clean neckline, no pattern — period.'},
{n:'Inverse H&S',cat:'chart',side:'bull',pts:[[2,70],[14,42],[24,58],[40,18],[56,58],[68,42],[80,58],[98,90]],lines:[[20,58,84,58]],arr:'up',
 read:'A capitulation low between two higher lows — the downtrend\u2019s last flush.',
 ctx:'Neckline break confirms; the right shoulder forming above the head\u2019s low is the tell.',
 trap:'Same disease in reverse: a sloppy neckline means you\u2019re drawing hope, not structure.'},
{n:'Ascending Triangle',cat:'chart',side:'bull',pts:[[2,30],[16,64],[30,40],[44,64],[56,48],[68,64],[78,56],[86,64],[96,86]],lines:[[12,64,88,64],[8,32,84,58]],arr:'up',
 read:'Flat ceiling, rising floor — buyers stepping up earlier on every dip.',
 ctx:'Pressure builds into the flat resistance; the classic resolution is up and through it.',
 trap:'"Classic" isn\u2019t "guaranteed" — failed triangles break hard the other way.'},
{n:'Descending Triangle',cat:'chart',side:'bear',pts:[[2,70],[16,36],[30,60],[44,36],[56,52],[68,36],[78,44],[86,36],[96,14]],lines:[[12,36,88,36],[8,68,84,42]],arr:'dn',
 read:'Flat floor, falling ceiling — sellers pressing lower into a defended level.',
 ctx:'Each weaker bounce drains the bid; the floor break is the textbook resolution.',
 trap:'In bull markets these break upward constantly. Trade the break, never the prediction.'},
{n:'Symmetrical Triangle',cat:'chart',side:'neut',pts:[[2,50],[14,76],[26,30],[38,68],[50,38],[60,62],[70,46],[78,56],[88,50],[97,72]],lines:[[10,78,86,52],[10,28,86,48]],arr:null,
 read:'Lower highs meeting higher lows — the spring coils, direction undecided.',
 ctx:'A continuation pattern more often than not; the prior trend gets the benefit of the doubt.',
 trap:'Breakouts in the final 10% of the apex are the least reliable. Early break > apex break.'},
{n:'Rising Wedge',cat:'chart',side:'bear',pts:[[2,18],[14,42],[24,30],[36,54],[46,44],[58,64],[68,56],[78,70],[86,64],[96,38]],lines:[[6,14,84,60],[8,46,84,72]],arr:'dn',
 read:'Price grinds higher inside converging lines — gains shrinking with every push.',
 ctx:'Rising on fading momentum is distribution in slow motion; the break is usually down.',
 trap:'Wedges can grind far longer than shorts can stay solvent. The break is the entry.'},
{n:'Falling Wedge',cat:'chart',side:'bull',pts:[[2,82],[14,58],[24,70],[36,46],[46,56],[58,36],[68,44],[78,30],[86,36],[96,62]],lines:[[6,86,84,40],[8,54,84,28]],arr:'up',
 read:'Price bleeds lower inside converging lines — each leg down losing force.',
 ctx:'Selling pressure exhausting itself; the upside break tends to be sharp.',
 trap:'"Losing momentum" still means falling. Knife-catching inside the wedge isn\u2019t the play.'},
{n:'Bull Flag',cat:'chart',side:'bull',pts:[[2,10],[20,72],[30,62],[38,68],[46,58],[54,64],[62,54],[95,92]],lines:[[26,72,66,58],[28,58,68,46]],arr:'up',
 read:'A sharp pole, then a tight drift against it — the market catching its breath.',
 ctx:'Continuation: the measured move projects the pole\u2019s length from the breakout.',
 trap:'A "flag" that retraces more than half the pole isn\u2019t resting — it\u2019s reversing.'},
{n:'Bear Flag',cat:'chart',side:'bear',pts:[[2,90],[20,28],[30,38],[38,32],[46,42],[54,36],[62,46],[95,8]],lines:[[26,28,66,42],[28,42,68,54]],arr:'dn',
 read:'A waterfall drop, then a weak upward drift — relief without conviction.',
 ctx:'The drift bleeds out shorts and traps dip-buyers before continuation lower.',
 trap:'Weak bounces can become V-reversals on news. Stops above the flag, always.'},
{n:'Cup & Handle',cat:'chart',side:'bull',pts:[[2,70],[12,52],[22,36],[34,28],[46,30],[58,40],[66,58],[72,70],[78,62],[84,66],[90,60],[97,86]],lines:[[4,70,90,68]],arr:'up',
 read:'A rounded base (the cup) plus a small dip near the rim (the handle).',
 ctx:'A long accumulation arc; the handle shakes out weak hands before the rim breaks.',
 trap:'Real cups take weeks to months. A "cup" formed in an afternoon is just a squiggle.'}
];
